[2021-04-20 07:07:27,194] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.run_quality_checks 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:07:27,223] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.run_quality_checks 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:07:27,224] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:07:27,225] {taskinstance.py:867} INFO - Starting attempt 2 of 4
[2021-04-20 07:07:27,226] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:07:27,280] {taskinstance.py:887} INFO - Executing <Task(DataQualityOperator): run_quality_checks> on 2018-11-01T00:00:00+00:00
[2021-04-20 07:07:27,284] {standard_task_runner.py:53} INFO - Started process 3445 to run task
[2021-04-20 07:07:27,387] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: global_dag.run_quality_checks 2018-11-01T00:00:00+00:00 [running]> 68b6afff5d68
[2021-04-20 07:07:27,429] {taskinstance.py:1128} ERROR - The conn_id `redshift` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/plugins/operators/data_quality.py", line 30, in execute
    records = redshift.get_records(check_query)[0]
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 115, in get_records
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 71, in get_conn
    conn = self.get_connection(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `redshift` isn't defined
[2021-04-20 07:07:27,433] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-04-20 07:07:37,159] {logging_mixin.py:112} INFO - [2021-04-20 07:07:37,158] {local_task_job.py:103} INFO - Task exited with return code 1
